### ISSUE TITLE
Erro na Importação do Banco

### ISSUE THREAD

**Issue by rickps2015** [rickps2015/Project-Arquitetura#3]
**Alguém sabe como resolver este tipo de erro na importação do Banco via SQL? (MariaDB)**

_Task 'MySQL restore' finished at Wed Mar 08 14:20:08 BOT 2023
2023-03-08 14:20:08.379 - IO error: Process failed (exit code = 1). See error log.
2023-03-08 14:20:08.379 - java.io.IOException: Process failed (exit code = 1). See error log.
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.validateErrorCode(AbstractNativeToolHandler.java:233)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.executeProcess(AbstractNativeToolHandler.java:213)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.doExecute(AbstractNativeToolHandler.java:273)
	at org.jkiss.dbeaver.ext.mysql.tasks.MySQLNativeToolHandler.doExecute(MySQLNativeToolHandler.java:47)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.lambda$0(AbstractNativeToolHandler.java:78)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)_

**Comment by rickps2015** [comment]
Aqui estão algumas etapas que você pode seguir para solucionar esse problema:

Verifique se o arquivo SQL está correto: Verifique se o arquivo SQL está correto e não contém erros de sintaxe ou outros problemas que possam estar impedindo sua importação para o banco de dados.

Verifique as permissões: Verifique se você tem permissão para importar o arquivo SQL no banco de dados. Certifique-se de que o usuário que está tentando importar o arquivo tem as permissões necessárias para criar e modificar tabelas.

Verifique a conexão do banco de dados: Verifique se a conexão com o banco de dados está correta e se o servidor do banco de dados está em execução. Certifique-se de que todas as configurações de conexão estejam corretas, como nome de usuário, senha, host, porta, etc.

Verifique o log de erros: O erro indica que há um log de erro que pode ajudar a identificar a causa do problema. Verifique o log de erros e procure por mensagens de erro que possam ajudá-lo a solucionar o problema.

Tente importar o arquivo SQL manualmente: Tente importar o arquivo SQL manualmente usando o utilitário de linha de comando do MySQL/MariaDB. Isso pode ajudá-lo a identificar problemas com o arquivo SQL ou com o processo de importação.

Tente uma ferramenta diferente: Se todas as outras opções falharem, tente usar uma ferramenta diferente para importar o arquivo SQL. Existem várias ferramentas disponíveis para importar arquivos SQL em bancos de dados MySQL/MariaDB, como o phpMyAdmin, HeidiSQL, MySQL Workbench, entre outros.

**Comment by rickps2015** [comment]
> Aqui estão algumas etapas que você pode seguir para solucionar esse problema:
> 
> Verifique se o arquivo SQL está correto: Verifique se o arquivo SQL está correto e não contém erros de sintaxe ou outros problemas que possam estar impedindo sua importação para o banco de dados.
> 
> Verifique as permissões: Verifique se você tem permissão para importar o arquivo SQL no banco de dados. Certifique-se de que o usuário que está tentando importar o arquivo tem as permissões necessárias para criar e modificar tabelas.
> 
> Verifique a conexão do banco de dados: Verifique se a conexão com o banco de dados está correta e se o servidor do banco de dados está em execução. Certifique-se de que todas as configurações de conexão estejam corretas, como nome de usuário, senha, host, porta, etc.
> 
> Verifique o log de erros: O erro indica que há um log de erro que pode ajudar a identificar a causa do problema. Verifique o log de erros e procure por mensagens de erro que possam ajudá-lo a solucionar o problema.
> 
> Tente importar o arquivo SQL manualmente: Tente importar o arquivo SQL manualmente usando o utilitário de linha de comando do MySQL/MariaDB. Isso pode ajudá-lo a identificar problemas com o arquivo SQL ou com o processo de importação.
> 
> Tente uma ferramenta diferente: Se todas as outras opções falharem, tente usar uma ferramenta diferente para importar o arquivo SQL. Existem várias ferramentas disponíveis para importar arquivos SQL em bancos de dados MySQL/MariaDB, como o phpMyAdmin, HeidiSQL, MySQL Workbench, entre outros.

ok
